build-image:
  stage: build

  before_script:
    - docker info
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_REGISTRY
    - echo $CI_PROJECT_NAMESPACE
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

  script:
    - ./build.sh -t ${CI_COMMIT_REF_NAME} -r ${CI_REGISTRY} -o ${CI_PROJECT_NAMESPACE}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}

  tags:
    - shell

